load("@io_bazel_rules_groovy//groovy:groovy.bzl", "groovy_binary")

groovy_binary(
    name = "hello-world",
    srcs = glob(["src/main/groovy/com/bmuschko/**/*.groovy"]),
    main_class = "com.bmuschko.HelloWorld"
)