load("//:java_abstraction.bzl", "versioned_java_library")

VERSION = "3.4.5"

versioned_java_library(
    name = "messenger",
    srcs = glob(["src/main/java/com/bmuschko/messenger/*.java"]),
    version = VERSION
)