# For more information, see https://docs.bazel.build/versions/master/be/pkg.html#pkg_tar
load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar")

pkg_tar(
    name = "my-tar",
    srcs = ["src"],
)